name: Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v2
      - users: actions/setup-node@v1
        with:
          node-version: 14.16.1
      - run: npm start
      - run: npm run test
      - uses: JamesIves/github-pages-deploy-actions@release/v3
        with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: .
